### PR TITLE
[api] Add timeout function

### PR DESCRIPTION
**Pull request by gichan-jang**
Tizen don't provide timeout util.
Add timeout function using perl.

Signed-off-by: Gichan Jang <gichan2.jang@samsung.com>

### CODE REVIEW

**Comment by myungjoo** [comment]
You have added dependency of PERL.
For Tizen, it's ok to use PERL if you add proper "Requires:" in .spec file.

However, PERL dependency should be optional. Can you make it depend on PERL 
1. timeout command is not found
2. perl is available.
3. If 1 = TRUE && 2 = FALSE, ignore timeout.


E.g., modify "```Timeout()```" so that it checks if the timeout command is available or not first.

**Comment by gichan-jang** [comment]
> You have added dependency of PERL.
> For Tizen, it's ok to use PERL if you add proper "Requires:" in .spec file.
> 
> However, PERL dependency should be optional. Can you make it depend on PERL
> 
> 1. timeout command is not found
> 2. perl is available.
> 3. If 1 = TRUE && 2 = FALSE, ignore timeout.
> 
> E.g., modify "`Timeout()`" so that it checks if the timeout command is available or not first.

Got it. I will update it.

**Review by myungjoo — APPROVED** [review]
LGTM!

Is this tested w/ gbs-build of nnstreamer-unittest?

**Comment by gichan-jang** [comment]
> LGTM!
> 
> Is this tested w/ gbs-build of nnstreamer-unittest?

Yes. I tested nnstreamer with gbs.
 - x86_64: pass all tests.
 - armv7l: pass all tests except nnstreamer_grpc.
                *grpc failure is not related to this change.

**Pull request merged**
